export const supplies = [
    {
      id: '1',
      firstName: "Minh",
      lastName: "Nguyen",
      phoneNumber: '0703350120',
      password: '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
      dob: "2002-10-15",
      gender: "male",
      address: "25 Đào Trí, Phường Phú Thuận, Quận 7, TP.HCM",  
      verified: false,
      avatar: 'https://example.com',
      email: "nguyenducminh@gmail.com",
      referralCode: '123'
    },
    {
      id: '2',
      firstName: "Khoa",
      lastName: "Nguyen",
      phoneNumber: '0703350121',
      password: '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
      dob: "2002-4-14",
      gender: "male",
      address: "1647 Phạm Thế Hiển, Phường 6, Quận 8, TP.HCM",  
      verified: true,
      avatar: 'https://example.com',
      email: "khoanguyen@gmail.com",
      referralCode: '123'
    },  
    {
      id: '3',
      firstName: "Huy",
      lastName: "Nguyen",
      phoneNumber: '0703350122',
      password: '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
      dob: "2002-10-15",
      gender: "male",
      address: "22 Huỳnh Đình Hai, Phường 24, Quận Bình Thạnh, TP.HCM",  
      verified: false,
      avatar: 'https://example.com',
      email: "huynguyen@gmail.com",
      referralCode: '123'
    },
    {
       id: '4',
       firstName: "Khang",
       lastName: "Dinh",
       phoneNumber: '0703350123',
       password: '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
       dob: "2002-4-21",
       gender: "male",
       address: "22 Đường Số 10, Phường Thảo Điền, Quận 2, TP.HCM",  
       verified: true,
       avatar: 'https://example.com',
       email: "khangdinh@gmail.com",
       referralCode: '123'
    },
    {
       id: '5',
       firstName: "Thanh",
       lastName: "Bui",
       phoneNumber: '0703350124',
       password: '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
       dob: "2002-10-15",
       gender: "male",
       address: "227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP.HCM",  
       verified: true,
       avatar: 'https://example.com',
       email: "thanhbui@gmail.com",
       referralCode: '123'
    },
];
