export const supplies = [
    {
        id: '1',
        firstName: 'Minh',
        lastName: 'Nguyen',
        password:
            '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
        dob: '2002-10-15',
        gender: 'male',
        address: '25 Đào Trí, Phường Phú Thuận, Quận 7, TP.HCM',
        verified: false,
        avatar: 'https://example.com',
        email: 'nguyenducminh@gmail.com',
    },
    {
        id: '2',
        firstName: 'Khoa',
        lastName: 'Nguyen',
        password:
            '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
        dob: '2002-4-14',
        gender: 'male',
        address: '1647 Phạm Thế Hiển, Phường 6, Quận 8, TP.HCM',
        verified: true,
        avatar: 'https://example.com',
        email: 'khoanguyen@gmail.com',
    },
    {
        id: '3',
        firstName: 'Huy',
        lastName: 'Nguyen',
        password:
            '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
        dob: '2002-10-15',
        gender: 'male',
        address: '22 Huỳnh Đình Hai, Phường 24, Quận Bình Thạnh, TP.HCM',
        verified: false,
        avatar: 'https://example.com',
        email: 'huynguyen@gmail.com',
    },
    {
        id: '4',
        firstName: 'Khang',
        lastName: 'Dinh',
        password:
            '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
        dob: '2002-4-21',
        gender: 'male',
        address: '22 Đường Số 10, Phường Thảo Điền, Quận 2, TP.HCM',
        verified: true,
        avatar: 'https://example.com',
        email: 'khangdinh@gmail.com',
    },
    {
        id: '5',
        firstName: 'Thanh',
        lastName: 'Bui',
        password:
            '$2a$04$4F68GFkr7Dt.hsRNRJ.dDeqixqtGMYrh0CKdMfdh1Y8EE9yHsnfam',
        dob: '2002-10-15',
        gender: 'male',
        address: '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP.HCM',
        verified: true,
        avatar: 'https://example.com',
        email: 'thanhbui@gmail.com',
    },
]
