version: "3"

services:
    # nginx:
    #   build:
    #     context: ./nginx
    #   hostname: nginx
    #   container_name: kabgo-nginx-proxy
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - ./nginx:/etc/nginx
    #   depends_on:
    #     - api-auth
    #     - api-driver
    #     - api-customer
    #     - api-admin
    #     - api-call-center
    #     - api-call-center-s2
    #     - api-call-center-s3
    #     - gps-coordinates
    #     - admin
    #     - call-center
    #     - rabbitmq

    demand-service:
        build:
            context: ../servers/demand
            dockerfile: Dockerfile.production
        image: wgmin/demand-service
        container_name: demand-service
        hostname: localhost
        networks:
            - proxy
        ports:
            - "5010:5001"
            - "50051:50051"
        environment:
            SUPPLY_GRPC_CLIENT_HOST: "supply.kabgo.mtech.id.vn"
            SUPPLY_GRPC_CLIENT_PORT: "50052"
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.demand-service.rule=Host(`demand.kabgo.mtech.id.vn`)
            - traefik.http.routers.demand-service.entrypoints=websecure
            - traefik.http.routers.demand-service.tls=true
            - traefik.http.routers.demand-service.tls.certresolver=letsencrypt
        restart: unless-stopped

    supply-service:
        build:
            context: ../servers/supply
            dockerfile: Dockerfile.production
        image: wgmin/supply-service
        container_name: supply-service
        hostname: localhost
        networks:
            - proxy
        ports:
            - "5020:5002"
            - "50052:50052"
        environment:
            DEMAND_GRPC_CLIENT_HOST: "demand.kabgo.mtech.id.vn"
            DEMAND_GRPC_CLIENT_PORT: "50051"
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.supply-service.rule=Host(`supply.kabgo.mtech.id.vn`)
            - traefik.http.routers.supply-service.entrypoints=websecure
            - traefik.http.routers.supply-service.tls=true
            - traefik.http.routers.supply-service.tls.certresolver=letsencrypt
        restart: unless-stopped

    admin-service:
        build:
            context: ../servers/admin
            dockerfile: Dockerfile.production
        image: wgmin/admin-service
        container_name: admin-service
        hostname: localhost
        ports:
            - "5030:5003"
            - "50053:50053"
        networks:
            - proxy
        environment:
            DEMAND_GRPC_CLIENT_HOST: "demand.kabgo.mtech.id.vn"
            DEMAND_GRPC_CLIENT_PORT: "50051"

            SUPPLY_GRPC_CLIENT_HOST: "supply.kabgo.mtech.id.vn"
            SUPPLY_GRPC_CLIENT_PORT: "50052"

            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.admin-service.rule=Host(`admin.kabgo.mtech.id.vn`)
            - traefik.http.routers.admin-service.entrypoints=websecure
            - traefik.http.routers.admin-service.tls=true
            - traefik.http.routers.admin-service.tls.certresolver=letsencrypt
        restart: unless-stopped

    admin-client:
        build:
            context: ../clients/admin
            dockerfile: Dockerfile.prod
            args:
                REACT_APP_BACKEND_HOST: "https://admin.kabgo.mtech.id.vn"
        image: wgmin/admin-client
        container_name: admin-client
        hostname: localhost
        networks:
            - proxy
        ports:
            - "3003:80"
        environment:
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.admin-client.rule=Host(`admin-panel.kabgo.mtech.id.vn`)
            - traefik.http.routers.admin-client.entrypoints=websecure
            - traefik.http.routers.admin-client.tls=true
            - traefik.http.routers.admin-client.tls.certresolver=letsencrypt
        restart: unless-stopped

    # rabbitmq:
    #   image: rabbitmq:3-management-alpine
    #   container_name: 'kabgo-rabbitmq'
    #   hostname: 'rabbitmq.kabgo.local'
    #   networks:
    #     - nw-rabbitmq
    #   ports:
    #       - "5672:5672"
    #       - "15672:15672"
    #   environment:
    #     FORCE_COLOR: 1
    #     DEBUG_COLORS: "true"
    #     TERM: xterm-256color
    #     COLORTERM: truecolor

    # api-auth:
    #   build:
    #     context: ../KabGo/servers/auth
    #   networks:
    #     - nw-api-auth
    #   hostname: api.auth.kabgo.local
    #   container_name: kabgo-auth
    #   ports:
    #     - "4100:4100"
    #   volumes:
    #     - ../KabGo/servers/auth:/usr/src/app
    #   environment:
    #     FORCE_COLOR: 1
    #     DEBUG_COLORS: "true"
    #     TERM: xterm-256color
    #     COLORTERM: truecolor

    # zookeeper:
    #     image: confluentinc/cp-zookeeper:latest
    #     container_name: kabgo-zookeeper
    #     ports:
    #         - 22181:2181
    #     environment:
    #         ZOOKEEPER_SERVER_ID: 1
    #         ZOOKEEPER_CLIENT_PORT: 2181
    #         ZOOKEEPER_TICK_TIME: 2000
    #         FORCE_COLOR: 1
    #         DEBUG_COLORS: "true"
    #         TERM: xterm-256color
    #         COLORTERM: truecolor

    # kafka:
    #     image: confluentinc/cp-kafka:latest
    #     container_name: kabgo-kafka
    #     depends_on:
    #         - zookeeper
    #     ports:
    #         - 29092:29092
    #     environment:
    #         KAFKA_BROKER_ID: 1
    #         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # zookeeper:
    #   image: 'zookeeper'
    #   restart: always
    #   hostname: zookeeper
    #   container_name: kabgo-zookeeper
    #   ports:
    #     - 2181:2181
    #   environment:
    #     - ALLOW_ANONYMOUS_LOGIN=yes
    #     - FORCE_COLOR=1
    #     - DEBUG_COLORS="true"
    #     - TERM=xterm-256color
    #     - COLORTERM=truecolor

    # kafka:
    #   image: 'bitnami/kafka'
    #   hostname: kafka.kabgo.local
    #   container_name: kabgo-kafka
    #   ports:
    #     - '9092:9092'
    #   environment:
    #     - KAFKA_CFG_BROKER_ID=1
    #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #     - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092
    #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
    #     - ALLOW_PLAINTEXT_LISTENER=yes
    #     - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
    #     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR='1'
    #     - KAFKA_CREATE_TOPICS='example-topic:1:1'
    #     - FORCE_COLOR=1
    #     - DEBUG_COLORS="true"
    #     - TERM=xterm-256color
    #     - COLORTERM=truecolor
    #   depends_on:
    #     - zookeeper

networks:
    proxy:
        external: true
