version: "3.4"

networks:
    kabgo-network:
        driver: bridge

services:
    # nginx:
    #   build:
    #     context: ./nginx
    #   hostname: nginx
    #   container_name: kabgo-nginx-proxy
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - ./nginx:/etc/nginx
    #   depends_on:
    #     - api-auth
    #     - api-driver
    #     - api-customer
    #     - api-admin
    #     - api-call-center
    #     - api-call-center-s2
    #     - api-call-center-s3
    #     - gps-coordinates
    #     - admin
    #     - call-center
    #     - rabbitmq

    demand-service:
        build:
            context: ../servers/demand
        container_name: demand-service
        hostname: localhost
        ports:
            - "5001:5001"
            - "50051:50051"
        networks:
            - kabgo-network
        volumes:
            - ../servers:/usr/src
            - ../servers/grpc:/usr/src/grpc
            - ../servers/demand:/usr/src/app
        environment:
            SUPPLY_GRPC_CLIENT_HOST: "supply-service"
            SUPPLY_GRPC_CLIENT_PORT: "50052"
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor

    supply-service:
        build:
            context: ../servers/supply
        container_name: supply-service
        hostname: localhost
        ports:
            - "5002:5002"
            - "50052:50052"
        networks:
            - kabgo-network
        volumes:
            - ../servers:/usr/src
            - ../servers/grpc:/usr/src/grpc
            - ../servers/supply:/usr/src/app
        environment:
            DEMAND_GRPC_CLIENT_HOST: "demand-service"
            DEMAND_GRPC_CLIENT_PORT: "50051"
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor

    admin-service:
        build:
            context: ../servers/admin
        container_name: admin-service
        hostname: localhost
        ports:
            - "5003:5003"
            - "50053:50053"
        networks:
            - kabgo-network
        volumes:
            - ../servers:/usr/src
            - ../servers/grpc:/usr/src/grpc
            - ../servers/admin:/usr/src/app
        environment:
            DEMAND_GRPC_CLIENT_HOST: "demand-service"
            DEMAND_GRPC_CLIENT_PORT: "50051"

            SUPPLY_GRPC_CLIENT_HOST: "supply-service"
            SUPPLY_GRPC_CLIENT_PORT: "50052"

            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor

    admin-client:
        build:
            context: ../clients/admin
        container_name: admin-client
        hostname: localhost
        ports:
            - "3003:3003"
        networks:
            - kabgo-network
        volumes:
            - ../clients/admin:/usr/src/app
        environment:
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor

    # rabbitmq:
    #   image: rabbitmq:3-management-alpine
    #   container_name: 'kabgo-rabbitmq'
    #   hostname: 'rabbitmq.kabgo.local'
    #   networks:
    #     - nw-rabbitmq
    #   ports:
    #       - "5672:5672"
    #       - "15672:15672"
    #   environment:
    #     FORCE_COLOR: 1
    #     DEBUG_COLORS: "true"
    #     TERM: xterm-256color
    #     COLORTERM: truecolor

    # api-auth:
    #   build:
    #     context: ../KabGo/servers/auth
    #   networks:
    #     - nw-api-auth
    #   hostname: api.auth.kabgo.local
    #   container_name: kabgo-auth
    #   ports:
    #     - "4100:4100"
    #   volumes:
    #     - ../KabGo/servers/auth:/usr/src/app
    #   environment:
    #     FORCE_COLOR: 1
    #     DEBUG_COLORS: "true"
    #     TERM: xterm-256color
    #     COLORTERM: truecolor

    # zookeeper:
    #   image: confluentinc/cp-zookeeper:latest
    #   container_name: kabgo-zookeeper
    #   ports:
    #     - 22181:2181
    #   environment:
    #     ZOOKEEPER_SERVER_ID: 1
    #     ZOOKEEPER_CLIENT_PORT: 2181
    #     ZOOKEEPER_TICK_TIME: 2000
    #     FORCE_COLOR: 1
    #     DEBUG_COLORS: "true"
    #     TERM: xterm-256color
    #     COLORTERM: truecolor

    # kafka:
    #   image: confluentinc/cp-kafka:latest
    #   container_name: kabgo-kafka
    #   depends_on:
    #     - zookeeper
    #   ports:
    #     - 29092:29092
    #   environment:
    #     KAFKA_BROKER_ID: 1
    #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    # zookeeper:
    #   image: 'zookeeper'
    #   restart: always
    #   hostname: zookeeper
    #   container_name: kabgo-zookeeper
    #   ports:
    #     - 2181:2181
    #   environment:
    #     - ALLOW_ANONYMOUS_LOGIN=yes
    #     - FORCE_COLOR=1
    #     - DEBUG_COLORS="true"
    #     - TERM=xterm-256color
    #     - COLORTERM=truecolor

    # kafka:
    #   image: 'bitnami/kafka'
    #   hostname: kafka.kabgo.local
    #   container_name: kabgo-kafka
    #   ports:
    #     - '9092:9092'
    #   environment:
    #     - KAFKA_CFG_BROKER_ID=1
    #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #     - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092
    #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
    #     - ALLOW_PLAINTEXT_LISTENER=yes
    #     - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
    #     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR='1'
    #     - KAFKA_CREATE_TOPICS='example-topic:1:1'
    #     - FORCE_COLOR=1
    #     - DEBUG_COLORS="true"
    #     - TERM=xterm-256color
    #     - COLORTERM=truecolor
    #   depends_on:
    #     - zookeeper
volumes:
    eventstore-volume-data:
    eventstore-volume-index:
    eventstore-volume-logs:

