# State 1: Build the React application
FROM node:alpine AS build
WORKDIR /usr/src/app 
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# State 2: Serve the React App with Docker
FROM nginx:alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

