FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .


WORKDIR /usr/src/grpc

COPY ./grpc ./

COPY ./grpc/package*.json ../


WORKDIR /usr/src

RUN npm ci

RUN npm run proto:generate

RUN cp -r ./grpc ./app


WORKDIR /usr/src/app

RUN npm run format-fix

RUN npm run build:prod


EXPOSE 5001 50051

CMD ["npm", "run", "start"]